name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:

      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/checkout@v3
        name: Clone x2on/OpenSSL-for-iPhone
        with:
          repository: 'x2on/OpenSSL-for-iPhone'
          path: 'openssl'
    
      - name: Build OpenSSL
        run: |
          cd openssl
          ./build-libssl.sh
      
      - name: Create XCFramework
        run: |
          cd openssl
          ./create-xcframework.sh
      
      - name: Compress XCFramework and Create Checksum
        run: |
          zip -ry ./openssl/OpenSSL.xcframework.zip ./openssl/OpenSSL.xcframework
          export TEMP=`shasum -a 256 openssl/OpenSSL.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP
      
      - name: Update Package.swift
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"OpenSSL\"," >> Package.swift
          echo "  platforms: [.iOS(.v12)]," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"OpenSSL\", targets: [\"OpenSSL\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"OpenSSL\"," >> Package.swift
          echo "      url: \"https://github.com/EbrahimTahernejad/OpenSSL-iOS/releases/download/${{ github.event.inputs.version }}/OpenSSL.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit Package.swift
        with:
          commit_message: OpenSSL-iOS Release ${{ github.event.inputs.version }}
          commit_user_name: Ebrahim
          commit_user_email: ebrahimtahernejad@gmail.com
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload XCFramework and Create Release Tag
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: openssl/OpenSSL.xcframework.zip
